CREATE PROC [DBO].[SP_GETBYMANV_NHANVIEN] 
	@MaNV VARCHAR(20)
AS
BEGIN
	SELECT [MaNV],
	[HoTen],
	[Email],
	CONVERT(VARCHAR(MAX), LUONG) AS [Luong],
	[TenDN],
	CONVERT(VARCHAR(MAX), MATKHAU) AS [MatKhau]
	FROM NHANVIEN
	WHERE MANV = @MaNV
END	